use Module::Build;
use strict;
use warnings;
use PDL::Core::Dev;

my $inc = PDL_INCLUDE;
$inc =~ s/^-I//;

#my $version = '0.01';

my $build = Module::Build->new(
	module_name => 'PDL::Fit::ExpRate',
	dist_version_from => 'lib/PDL/Fit/ExpRate.pm.PL',
	license  => 'perl',
	requires => {
		perl					=> '5.6.1',
		PDL						=> 2,
	},
	needs_compiler => 1,
	include_dirs => $inc,
);

$build->create_build_script;
