---
abstract: 'fitting noisy exponential decay'
author:
  - 'David Mertens <dcmertens.perl@gmail.com>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDL-Fit-ExpRate
provides:
  PDL::PP::Include::Fit::ExpRate:
    file: lib/PDL/PP/Include/Fit/ExpRate.pm
    version: 0
requires:
  PDL: 2
  perl: v5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
